# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    resolvers:
        default:
            web_path: ~

    filter_sets:
        cache: ~
        profile:
            quality: 100
            filters:
                thumbnail: { size: [300, 300], mode: inset, allow_upscale: true }
        
        thumb:
            quality: 75
            filters:
                thumbnail: { size: [70,70], mode: inset, allow_upscale: true }